### ISSUE TITLE
希望作者能看到

### ISSUE THREAD

**Issue by mutouzhang** [jemygraw/GoQuickLearn-iOS#1]
求教，作者的android版代码是用什么来显示的？自己写的view吗，还是textView展示html文本？因为在页面显示上并没有出现textview加载大量汉字文本出现的换行错位问题，而且黑色背景的代码真是太漂亮了，希望作者不吝赐教。

**Comment by jemygraw** [comment]
markdown编写内容，然后转换为html，代码高亮是js和css做的。用的是WebView
